# Generated by Django 3.0.9 on 2020-08-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                (
                    "add_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="date added"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(auto_now=True, verbose_name="date modified"),
                ),
            ],
        ),
    ]
