# Generated by Django 3.0.9 on 2020-08-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
